default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: chipoverflow_dev

test:
  <<: *default
  database: chipoverflow_test

production:
  <<: *default
  database: chipoverflow_prod
  url: <%= ENV['DATABASE_URL'] %>
